# Equipment Service - Production Profile

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:5432/equipment_db
    username: ${DB_USERNAME}
    password: '{cipher}${DB_PASSWORD_ENCRYPTED}'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  rabbitmq:
    host: ${RABBITMQ_HOST:prod-rabbitmq-server}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: '{cipher}${RABBITMQ_PASSWORD_ENCRYPTED}'

feign:
  client:
    config:
      farmers-service:
        url: ${FARMERS_SERVICE_URL}

logging:
  level:
    root: WARN
    com.farm.equipment: INFO
