# Farmers Service - Production Profile

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:5432/farmers_db
    username: ${DB_USERNAME}
    password: '{cipher}${DB_PASSWORD_ENCRYPTED}'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.farm.farmers: INFO

# Production-specific security
server:
  ssl:
    enabled: false  # Enable in production with actual certificates
